[package]
name = "schach"
version = "0.1.0"
authors = ["Lorenz Lutz <lorenz@mklutz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
