#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."

rm -Rf build
mkdir build
cd build
cmake --configure ..
cmake --build .
